-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.entries
(
    entry_id serial NOT NULL,
    flavour character varying(256) COLLATE pg_catalog."default" NOT NULL,
    datum date NOT NULL,
    amount money NOT NULL,
    vak character varying(256) COLLATE pg_catalog."default",
    CONSTRAINT entries_pkey PRIMARY KEY (entry_id)
);

CREATE TABLE IF NOT EXISTS public.flavours
(
    flavour_id serial NOT NULL,
    naam character varying(256) COLLATE pg_catalog."default" NOT NULL,
    se boolean NOT NULL,
    not_rb boolean NOT NULL,
    CONSTRAINT flavours_pkey PRIMARY KEY (flavour_id),
    CONSTRAINT flavours_naam_key UNIQUE (naam)
);

CREATE TABLE IF NOT EXISTS public.vak
(
    vak_id serial NOT NULL,
    naam character varying(256) COLLATE pg_catalog."default" NOT NULL,
    schooljaar character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT vak_pkey PRIMARY KEY (vak_id),
    CONSTRAINT vak_naam_key UNIQUE (naam)
);

ALTER TABLE IF EXISTS public.entries
    ADD CONSTRAINT entries_flavour_fkey FOREIGN KEY (flavour)
    REFERENCES public.flavours (naam) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.entries
    ADD CONSTRAINT entries_vak_fkey FOREIGN KEY (vak)
    REFERENCES public.vak (naam) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
